#!/bin/bash


qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 1000 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 64 --num_lstm_layers 2 --embedding_dimension 128 --task NER" plan_base_cv04.sh

qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 1000 --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 64 --num_lstm_layers 2 --embedding_dimension 128 --task NER" plan_base_cv04.sh

qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --logging_steps 50 --learning_rate 0.001 --warmup_steps 4000 --num_train_epochs 1000 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 64 --num_lstm_layers 2 --embedding_dimension 128 --task NER" plan_base_cv04.sh

qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 1000 --no_bias --dropout_probs 0.05 --l2_alpha 0 --lstm_hidden_dimension 64 --num_lstm_layers 2 --embedding_dimension 128 --task NER" plan_base_cv04.sh

qsub -v args="--model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 1000 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128" plan_base_cv04.sh

qsub -v args="--model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 1000 --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128" plan_base_cv04.sh

qsub -v args="--model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.001 --warmup_steps 4000 --num_train_epochs 1000 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128" plan_base_cv04.sh

qsub -v args="--model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data --labels /storage/plzen1/home/vladar21/nlp-cv04/data/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 200 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 1000 --no_bias --dropout_probs 0.05 --l2_alpha 0 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128" plan_base_cv04.sh


qsub -v args="--model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 10 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh

qsub -v args="--model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 10 --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh

qsub -v args="--model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.001 --warmup_steps 4000 --num_train_epochs 10 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh

qsub -v args="--model_type RNN --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --eval_dataset_batches 200 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 10 --no_bias --dropout_probs 0.05 --l2_alpha 0 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh

qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 10 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh

qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 10 --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh

qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --logging_steps 50 --learning_rate 0.001 --warmup_steps 4000 --num_train_epochs 10 --no_bias --dropout_probs 0.05 --l2_alpha 0.01 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh

qsub -v args="--per_device_train_batch_size 8 --per_device_eval_batch_size 8 --model_type LSTM --data_dir /storage/plzen1/home/vladar21/nlp-cv04/data-mt --labels /storage/plzen1/home/vladar21/nlp-cv04/data-mt/labels.txt --output_dir /storage/plzen1/home/vladar21/nlp-cv04/output --do_predict --do_train --do_eval --eval_steps 300 --logging_steps 50 --learning_rate 0.0001 --warmup_steps 4000 --num_train_epochs 10 --no_bias --dropout_probs 0.05 --l2_alpha 0 --lstm_hidden_dimension 128 --num_lstm_layers 2 --embedding_dimension 128 --task TAGGING" plan_base_cv04.sh